//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Dept_Master
    {
        public long ID { get; set; }
        public long EmpID { get; set; }
        public long DeptID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
